```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, eval = FALSE)
```

# R包发邮件

## 利用`blastula`包发邮件

这个包可以使用markdown形式创造邮件内容，比较美观。

先创造邮件的主体内容，参考作者github的说明如下：

```{r}
# Get a nicely formatted date/time string
date_time <- add_readable_time()

# Create an image string using an on-disk
# image file
img_file_path <-
  system.file(
    "img", "pexels-photo-267151.jpeg",
    package = "blastula"
  )

img_string <- add_image(file = img_file_path)

# 使用compose_email函数，以及md函数，还有glue函数构造
email <-
  compose_email(
    body = md(glue::glue(
"Hello,

This is a *great* picture I found when looking
for sun + cloud photos:

{img_string}
")),
    footer = md(glue::glue("Email sent on {date_time}."))
  )

# 还可以如下形式添加附件
# email <- add_attachment(email, file = '你的文件')
```

然后开始对邮箱进行设置。国内的邮箱都差不多，我尝试了新浪和QQ。
```{r}
# 这个命令执行时，会弹出一个窗口，让你填写邮箱的授权码。设好以后，今后发送邮件直接调这个文件就可以了
create_smtp_creds_file(file = '~/Downloads/sina_creds', # 创造认证文件sina_creds放到你想放的位置
                       user = 'example@sina.com', # 你的邮箱地址
                       host = 'smtp.sina.com', # 新浪邮箱服务器，如果是QQ邮箱，则将sina改成qq
                       port = 465, # 默认端口，sina和QQ都是这个，估计国内都是这个
                       use_ssl = T)
# 发送成功
email |> smtp_send(to = 'example@qq.com', # 可以是向量
                   from = 'example@sina.com',
                   subject = "Testing the `smtp_send()` function", # 邮件的标题
                   credentials = creds_file("~/Downloads/sina_creds"))
```


## 利用`mailR`包发送邮件

```{r}
send.mail(from = 'example@sina.com',
          to = 'example@qq.com',
          subject="Subject of the email",
          body = "Body of the email", # 邮件内容
          smtp = list(host.name = "smtp.sina.com", port = 465, 
                      passwd = 'xxxxx', user.name = 'example@sina.com',ssl = TRUE), # passwd就是授权码
          authenticate = TRUE,
          send = TRUE,
          # attach.files = '~/我的文件.pdf',
          encoding = 'utf-8')
```

